#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

// use JoshBruce\Site\SiteDynamic\Generator as DynamicGenerator;
use JoshBruce\SiteStatic\Generator as StaticGenerator;

$application = new Application();

// $application->add(new DynamicGenerator());

$application->add(new StaticGenerator());

$application->run();
