#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

use JoshBruce\Console\StaticSite;

$application = new Application();

$application->add(new StaticSite());

$application->run();
